### ISSUE TITLE
cannot validate webhooks (401 error) and therefore cannot run app

### ISSUE THREAD

**Issue by CK-Ward** [nearform/zoom-shuffle-bot#327]
Hi, I'm trying to setup a chat app and it looks like the Zoom documentation has been updated since the README was last updated. Basically, adding an Event Subscription has "Validate" buttons now to validate the webhook. These do not work and give 401 errors. Unfortunately, this means I cannot test the app locally because it requires webhooks to be validated before I can hit the "Add" button. 

![image](https://user-images.githubusercontent.com/28264990/213599427-044a7285-2916-4498-8464-a47de6e6c28d.png)

Which leads to...

![image](https://user-images.githubusercontent.com/28264990/213599469-2e096dc6-4b9d-4fec-b915-20a3796b004b.png)

As a heads up! The goal is to make a fun contribution to this project soon, using a Node.js version of https://github.com/ngrok/ngrok-go (coming soon to an npm package near you) to embed ngrok tunnel creation in chatbot.js :) 

<details><summary>Here's my stdout</summary>
[17:31:25.321] INFO (14960): Server listening at http://0.0.0.0:3000
[17:33:51.369] INFO (14960): incoming request
    reqId: "req-1"
    req: {
      "method": "POST",
      "url": "/hook",
      "hostname": "devgro-zoom-shuffle.ngrok.io",
      "remoteAddress": "127.0.0.1",
      "remotePort": 55419
    }
[17:33:51.371] INFO (14960): Unauthorized
    reqId: "req-1"
    res: {
      "statusCode": 401
    }
    err: {
      "type": "UnauthorizedError",
      "message": "Unauthorized",
      "stack":
          UnauthorizedError: Unauthorized
              at verifyRequest (file:///Users/celina/ngrok-stuff/zoom-shuffle-bot/plugins/verifyRequest.js:10:11)
              at hookIterator (/Users/celina/ngrok-stuff/zoom-shuffle-bot/node_modules/fastify/lib/hooks.js:246:10)
              at next (/Users/celina/ngrok-stuff/zoom-shuffle-bot/node_modules/fastify/lib/hooks.js:174:16)
              at hookRunner (/Users/celina/ngrok-stuff/zoom-shuffle-bot/node_modules/fastify/lib/hooks.js:196:3)
              at Object.routeHandler [as handler] (/Users/celina/ngrok-stuff/zoom-shuffle-bot/node_modules/fastify/lib/route.js:469:7)
              at Router.callHandler (/Users/celina/ngrok-stuff/zoom-shuffle-bot/node_modules/find-my-way/index.js:413:14)
              at Router.lookup (/Users/celina/ngrok-stuff/zoom-shuffle-bot/node_modules/find-my-way/index.js:391:17)
              at Server.preRouting (/Users/celina/ngrok-stuff/zoom-shuffle-bot/node_modules/fastify/fastify.js:773:14)
              at Server.emit (node:events:513:28)
              at parserOnIncoming (node:_http_server:1061:12)
      "status": 401,
      "statusCode": 401,
      "expose": true
    }
[17:33:51.380] INFO (14960): request completed
    reqId: "req-1"
    res: {
      "statusCode": 401
    }
    responseTime: 10.50583267211914

</details>

**Comment by simoneb** [comment]
Also relevant is the context where that function is called, as when the operation sent by zoom is the endpoint validation, we short circuit the business logic inside the webhook.

```js
if (isValidZoomRequest(request)) {
    // webhook validation request from Zoom
    if (request.body?.event === 'endpoint.url_validation') {
      const hashForValidation = createHmac(
        'sha256',
        process.env.ZOOM_WEBHOOK_SECRET_TOKEN
      )
        .update(request.body.payload.plainToken)
        .digest('hex')

      return response.json({
        plainToken: request.body.payload.plainToken,
        encryptedToken: hashForValidation
      })
    }

  // rest of the business logic
```

**Comment by CK-Ward** [comment]
Awesome, thanks @simoneb. I'll try that next and will submit a PR if I do get it working.

**Comment by CK-Ward** [comment]
@simoneb so, based on testing, I _think_ I've figured out where to put this logic, in [verifyRequest.js](https://github.com/nearform/zoom-shuffle-bot/blob/master/plugins/verifyRequest.js). That being said, I can't figure out why `request.body`'s value is `undefined`. I am not too familiar with fastify so there might be a gap in my understanding there, though I can verify with ngrok in localhost:4040 that the body is indeed coming through, so my guess is that it's getting dropped somewhere in the code.

<img width="602" alt="image" src="https://user-images.githubusercontent.com/28264990/213895892-add5af24-2c90-434c-b97f-452c9e539f62.png">


 I have tried to trace the codepath upstream, and attempted to log the request body [here in plugins/zoom.js](https://github.com/nearform/zoom-shuffle-bot/blob/master/plugins/zoom.js#L13) before `verifyRequest(...)` gets called, to no avail. I am not sure where to check next. Want to note that `request.headers` values show up as expected. Unfortunately, without the body, I am unable to move forward. Any tips here would be appreciated! 
 
 <details><summary>Here is my stdout</summary>
 
 ```
 /opt/homebrew/bin/node /Users/celina/ngrok-stuff/zoom-shuffle-bot/chatbot.js
[17:04:59.161] INFO (61407): Server listening at http://0.0.0.0:3000
[17:05:24.834] INFO (61407): incoming request
    reqId: "req-1"
    req: {
      "method": "POST",
      "url": "/hook",
      "hostname": "devgro-zoom-shuffle.ngrok.io",
      "remoteAddress": "127.0.0.1",
      "remotePort": 58330
    }
[17:05:24.837] ERROR (61407): The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    reqId: "req-1"
    req: {
      "method": "POST",
      "url": "/hook",
      "hostname": "devgro-zoom-shuffle.ngrok.io",
      "remoteAddress": "127.0.0.1",
      "remotePort": 58330
    }
    res: {
      "statusCode": 500
    }
    err: {
      "type": "TypeError",
      "message": "The \"key\" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined",
      "stack":
          TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
              at new NodeError (node:internal/errors:399:5)
              at prepareSecretKey (node:internal/crypto/keys:587:11)
              at new Hmac (node:internal/crypto/hash:136:9)
              at createHmac (node:crypto:172:10)
              at isValidZoomRequest (file:///Users/celina/ngrok-stuff/zoom-shuffle-bot/plugins/verifyRequest.js:38:25)
              at verifyRequest (file:///Users/celina/ngrok-stuff/zoom-shuffle-bot/plugins/verifyRequest.js:5:7)
              at hookIterator (/Users/celina/ngrok-stuff/zoom-shuffle-bot/node_modules/fastify/lib/hooks.js:246:10)
              at next (/Users/celina/ngrok-stuff/zoom-shuffle-bot/node_modules/fastify/lib/hooks.js:174:16)
              at hookRunner (/Users/celina/ngrok-stuff/zoom-shuffle-bot/node_modules/fastify/lib/hooks.js:196:3)
              at Object.routeHandler [as handler] (/Users/celina/ngrok-stuff/zoom-shuffle-bot/node_modules/fastify/lib/route.js:469:7)
      "code": "ERR_INVALID_ARG_TYPE"
    }
[17:05:24.842] INFO (61407): request completed
    reqId: "req-1"
    res: {
      "statusCode": 500
    }
    responseTime: 7.248540878295898

```
</details>

Also, would love to push a branch with my in-progress work, but it looks like repo permissions might need to be updated for that :) 

<img width="823" alt="image" src="https://user-images.githubusercontent.com/28264990/213896044-31b60f32-697a-4b53-9966-36ea90965c8e.png">

**Comment by simoneb** [comment]
Hi @CK-Ward , I'm sorry that you're having all these troubles getting this to run. I admit that although we open sourced this repo, it was originally intended for our own internal use, so there is a chance that some steps are not documented properly, especially considering the changes that Zoom did to the workings of Webhooks since we implemented this. 

To answer your last question, you can't push to this repo, you'll have to create your own fork and then push to it. If you do that, we can take a look at your code and try to figure out what might be going wrong. Note that several environment variables need to be populated to the app to work, with values coming from the Zoom app you will need to create. This should already be documented in the readme.

**Comment by CK-Ward** [comment]
@simoneb ok, thanks. so I've made some progress at https://github.com/CK-Ward/zoom-shuffle-bot/pull/1/files. I found out via [fastify's hook docs ](https://www.fastify.io/docs/latest/Reference/Hooks/#prevalidation)that we'll want to use `preValidation` instead of `onRequest` if we intend to keep `verifyRequest(...)`,  because `onRequest` intentionally drops the `.body` value of the request. However, I couldn't quite figure out how to pass in the `res` value upon looking at how verifyRequest is used in `zoom.js` [in the decorator in plugins/zoom.js](https://github.com/CK-Ward/zoom-shuffle-bot/blob/master/plugins/zoom.js#L64), so I just commented out the verification step entirely for the purposes of validation, and handled the logic directly in `/hook`. 

There's also a new `SECRET_TOKEN` in the environment variables. 

I am waiting for administration modifications so that I can have permissions to install the app in the workspace. In the meantime, thank you for your help thus far. 🙏

**Comment by RomuloVitoi** [comment]
@CK-Ward we've just merged a PR with the changes necessary for the webhook validation and the use of the secret token instead of the deprecated validation token, could you give it a try and let us know if it solved the problem that you were facing?

**Comment by CK-Ward** [comment]
@RomuloVitoi, thank you so much for incorporating this change! I was out at a company offsite all last week (where I secured admin access to install this app in our company workspace!), so this is really perfect timing. 

The code changes work minus 1 caveat: the `clientId` value from the `req.headers` when validating the hook from the "Feature" tab when adding a new Event Subscription doesn't seem to exist from the raw payload, so commenting that out makes validation work as expected. 

<details><summary>raw payload</summary>

```POST /hook HTTP/1.1
Host: devgro-zoom-shuffle.ngrok.io
User-Agent: Zoom Marketplace/1.0a
Content-Length: 110
Authorization: <REDACTED>
Content-Type: application/json; charset=utf-8
X-Forwarded-For: 3.235.83.101
X-Forwarded-Proto: https
X-Zm-Request-Timestamp: 1675877891
X-Zm-Signature: v0=<REDACTED>
Accept-Encoding: gzip

{"payload":{"plainToken":"<REDACTED>"},"event_ts":1675877891837,"event":"endpoint.url_validation"}
```
</details>

That all works fine. I also see events successfully being processed when folks leave/join meetings. That being said, when I run the app and type the `/shuffle` command into the team chat to trigger the `/bot` hook, I get a `500` error: 

```
[09:48:35.068] INFO (43648): incoming request
    reqId: "req-k"
    req: {
      "method": "POST",
      "url": "/bot",
      "hostname": "devgro-zoom-shuffle.ngrok.io",
      "remoteAddress": "127.0.0.1",
      "remotePort": 54735
    }
[09:48:35.097] ERROR (43648): Cannot read properties of undefined (reading 'refresh_token')
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'refresh_token')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'refresh_token')
              at getApiToken (file:///Users/celina/ngrok-stuff/zoom-shuffle-bot/plugins/zoom.js:28:21)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Object.fetch (file:///Users/celina/ngrok-stuff/zoom-shuffle-bot/plugins/zoom.js:67:21)
              at async Object.<anonymous> (file:///Users/celina/ngrok-stuff/zoom-shuffle-bot/routes/bot.js:38:27)
    }
```

Since I'm getting 200s now, though, I'm going to work on embedding ngrok-node into the app directly at this point (since we're ready to test installing from npm today!). I'll take a look at the `/bot` hook afterward. 

Looking forward to using this app :)
